quarkus:
  http:
    port: 8081
  swagger-ui:
    path: /api
    always-include: true

currency-quote-api/mp-rest/url: https://economia.awesomeapi.com.br
currency-quote-api/mp-rest/scope: javax.inject.Singleton
